# Generated by Django 5.0.6 on 2026-07-27 14:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('language', models.CharField(choices=[('ur', 'Urdu'), ('en', 'English'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('category', models.CharField(blank=True, choices=[('garbage', 'Garbage'), ('roads', 'Broken Roads'), ('water', 'Water Shortage'), ('sewer', 'Sewer Problem'), ('electricity', 'Electricity Outage'), ('streetlights', 'Street Lights'), ('illegal_dumping', 'Illegal Dumping'), ('cleanliness', 'Public Cleanliness'), ('other', 'Other')], help_text='Null until Gemini classification completes (FR19).', max_length=30, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('in_review', 'In Review'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='received', max_length=20)),
                ('priority_score', models.FloatField(blank=True, help_text='Null until Gemini priority estimation completes (FR19).', null=True)),
                ('embedding', models.JSONField(blank=True, help_text='Sentence Transformer embedding vector, stored as a JSON array of floats. Not pgvector in MVP — see Phase 2 tradeoffs.', null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('image', models.ImageField(blank=True, null=True, upload_to='complaints/%Y/%m/')),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='ai_engine.cluster')),
                ('duplicate_of', models.ForeignKey(blank=True, help_text='Set when duplicate-detection links this to an existing complaint.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='complaints.complaint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'complaints_complaint',
            },
        ),
        migrations.CreateModel(
            name='ComplaintStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('old_status', models.CharField(choices=[('received', 'Received'), ('in_review', 'In Review'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], max_length=20)),
                ('new_status', models.CharField(choices=[('received', 'Received'), ('in_review', 'In Review'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], max_length=20)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='complaints.complaint')),
            ],
            options={
                'db_table': 'complaints_status_history',
            },
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status'], name='complaints__status_7c8de0_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['category'], name='complaints__categor_8115a1_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['created_at'], name='complaints__created_805464_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['latitude', 'longitude'], name='complaints__latitud_7c96e8_idx'),
        ),
    ]
