# Generated by Django 5.0.6 on 2026-07-27 14:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=50)),
                ('centroid_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('centroid_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('complaint_count', models.PositiveIntegerField(default=0)),
                ('priority_score', models.FloatField(blank=True, null=True)),
                ('summary_text', models.TextField(blank=True, null=True)),
                ('is_hotspot', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ai_engine_cluster',
                'indexes': [models.Index(fields=['is_hotspot'], name='ai_engine_c_is_hots_596e31_idx'), models.Index(fields=['category'], name='ai_engine_c_categor_b40c27_idx')],
            },
        ),
    ]
